version: "3"
services:
  mysql:
    image: percona/percona-server
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    command: "mysqld --character-set-server=UTF8MB4 --default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 13306:3306
    restart: always
volumes:
  mysql-data: